### ISSUE TITLE
请问如何修改成不显示根目录而是指定文件夹呢？

### ISSUE THREAD

**Issue by billy74** [Tai7sy/OneDriveFly#1]
按照教程已经搭建成功，但是请问如何修改成不显示根目录而是指定文件夹呢？
是修改这里么？
![qiujie](http://file.mzfree.top/img/2019/04/kuLtocROo3.jpg "修改了好像没效果")

**Comment by Tai7sy** [comment]
新版本已经支持, 修改`config`的 `list_path` 即可
