### ISSUE TITLE
程序各种异常报错

### ISSUE THREAD

**Issue by tyj9713** [Tai7sy/OneDriveFly#10]
常见的情况有
1，超时
2，Warning: Invalid argument supplied for foreach() in /var/user/index.php on line 244 Warning: Invalid argument supplied for foreach() in /var/user/index.php on line 259
3，{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Exception: failed to get access_token. in /var/user/index.php:61\nStack trace:\n#0 /var/user/index.php(90): fetch_files('/OneDrive/%E6%9...')\n#1 /var/user/index.php(32): list_files('/%E6%95%99%E7%A...')\n#2 /var/runtime/php7/bootstrap.php(41): main_handler(Array, Object(stdClass))\n#3 /var/runtime/php7/bootstrap.php(177): __scf_bootstrap_\\EventHandler-\u003ehandle(Object(stdClass), Object(stdClass))\n#4 /var/runtime/php7/bootstrap.php(200): __scf_bootstrap_\\__main_for_scf()\n#5 {main}"}

这该怎么解决

**Comment by Tai7sy** [comment]
刷新解决
