### ISSUE TITLE
未来计划功能

### ISSUE THREAD

**Issue by insoxin** [Tai7sy/OneDriveFly#11]
推荐大佬参考
github.com/WangNingkai/OLAINDEX

OneDrive 目录查看索引分页查看；
支持代码、图片、文本文件即时预览、图片列表栏展示；
支持音视频播放（兼容大部分格式），视频播放采用 Dplayer.js，音乐播放采用 Aplayer；
支持自定义创建文件夹、文件夹加密、文件/文件夹删除、文件/文件夹的复制与移动；
支持文件搜索、文件上传、文件直链分享与删除、文件直链一键下载；
支持管理 readme/head 说明文件；
支持图床；
支持命令行操作；
支持文件离线下载（个人版）；
后台基本显示管理，多主题管理，文件预览管理等等（清理缓存后及时生效）；
支持世纪互联；
支持多种缓存系统（Redis、Memcached等）；
更多功能欢迎亲自尝试。
注： 部分功能需登录。

**Comment by Tai7sy** [comment]
命令行和离线下载这类scf云函数无法支持，其余功能都是细节上的，没有难度。
至于Redis、Memcached这些缓存可以实现，但这些云数据库可不是一般贵。。。。

**Comment by insoxin** [comment]
@Tai7sy 大佬 收费的可以阉割 /手动滑稽

**Comment by Tai7sy** [comment]
#12
