### ISSUE TITLE
不支持个人版微软账号吗？

### ISSUE THREAD

**Issue by icedifferent** [Tai7sy/OneDriveFly#15]
AADSTS50020: User account '7428xxx@qq.com' from identity provider 'live.com' does not exist in tenant '默认目录' and cannot access the application '298004f7-c751-4d56-aba3-b058c0154fd2'(OneDrive API) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

**Comment by icedifferent** [comment]
然后我添加了一个租户。然后又报了：e?error=access_denied&error_description=AADSTS650051%3a+Using+application+%27OneDrive+API%27+is+currently+not+supported+for+your+organization+lujianzeng.com+because+it+is+in+an+unmanaged+state.+An+administrator+needs+to+claim+ownership+of+the+company+by+DNS+validation+of+lujianzxxxx.com+before+the+application+OneDrive+API+can+be+provisioned.%0d%0aTrace+ID%3a+5fce01ca-5b52-4a1d-99ba-8a37ec032000%0d%0aCorrelation+ID%3a+3611f686-b627-4299-811c-f314abdb3461%0d%0aTimestamp%3a+2019-07-20+09%3a42%3a10Z

**Comment by Tai7sy** [comment]
微软的报错说明写的很明确了，自己翻译一下就看懂了

**Comment by icedifferent** [comment]
> 
> 
> 微软的报错说明写的很明确了，自己翻译一下就看懂了

抱歉：之前你说是没有管理员，但是我主要不是很清楚如何解决，

**Comment by Tai7sy** [comment]
如果你没有此账号的管理员，那么此账号无法使用onedrive api，个人版应该不支持了

**Comment by icedifferent** [comment]
> 如果你没有此账号的管理员，那么此账号无法使用onedrive api，个人版应该不支持了

看样子我之前是没有修改你程序中写死了的app ID,我自己注册了应用之后，然后在程序中修改成我的app ID,在授权的时候，点击绑定依旧继续跳转到...https://login.microsoftonline.com/login.srf (无限循环)。想问一下这是什么原因导致的？

**Comment by icedifferent** [comment]
Get a refresh_token的链接为：https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=5cb1cf87-dca5-4401-a874-44ec37519640&redirect_uri=http://localhost/authorization_code，

点击之后跳转到：https://login.microsoftonline.com/common/oauth2/authorize?response_type=code&client_id=5cb1cf87-dca5-4401-a874-44ec37519640&redirect_uri=http://localhost/authorization_code
然后点击登录账号之后跳转到：
https://login.live.com/login.srf?wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=estsredirect%3d2%26estsrequest%3drQIIAdNiNtQztFIxTU4yTE6zMNdNSU401TUxMTDUTbQwNwGyUpONzU0NLc1MDIqEuASajx2MPPHwi_P-Z6Lix79...kfEWE7-_Y2lJhhGIyC_KrErdxMyWnJ-bm593g5nxAgvjKxYmA74fLIyLWIHGzMnuafyxqs1rrVZAR92SPoZTrPo5fk7BhvmF5c6-bmb6Bm4BaUmmnqUFiU...e61517c7f62813&username=74...0157%40qq.com,

然后重定向到：
https://login.microsoftonline.com/login.srf

**Comment by qkqpttgf** [comment]
https://github.com/qkqpttgf/OneDrive_SCF
已经支持
