### ISSUE TITLE
一个文件夹有1333个文件，13G，密码失效。

### ISSUE THREAD

**Issue by platoer** [Tai7sy/OneDriveFly#17]
如题。
其它文件夹正常。

**Comment by qkqpttgf** [comment]
我的demo里面73buyershow也是很多文件的，刚刚测试了一下，好像没有问题，你有hostloc帐号吗？在论坛pm我你QQ号，我远程看看。

**Comment by platoer** [comment]
> 我的demo里面73buyershow也是很多文件的，刚刚测试了一下，好像没有问题，你有hostloc帐号吗？在论坛pm我你QQ号，我远程看看。

没有你说的账户，另外QQ也好多年不用了：） 
我觉得是我这个文件夹的文件名（Calibre Library数据库）和密码文件命导致的，我换一下PW文件名试试。

![image](https://user-images.githubusercontent.com/27715615/61788621-19c79f00-ae45-11e9-807b-f0c92746c42a.png)

**Comment by qkqpttgf** [comment]
带空格的文件名，我要试下，话说我的demo好像下午刷太多，
> Exception: failed to get access_token
了

**Comment by platoer** [comment]
嗯，可能就是文件名格式问题造成的

**Comment by qkqpttgf** [comment]
是的，带空格的目录在urlencode时变成了+，临时在代码中替换+为%20，请去我分支看下
（但有+的目录又怎么办……）

**Comment by platoer** [comment]
分支？ 您的Demo网盘还是说在Github？

**Comment by qkqpttgf** [comment]
随便哪都行
