### ISSUE TITLE
啥时候支持一下在线播放呢？

### ISSUE THREAD

**Issue by eicky** [Tai7sy/OneDriveFly#2]
请问后期能支持在线播放吗

**Comment by Tai7sy** [comment]
图片或者文本在线预览比较简单可以实现，
视频在线播放建议用专业的播放器选择在线地址。
各种各样的视频格式限制了在网页中进行管理

**Comment by dahuajiz** [comment]
请问怎样实现图片的在线预览呢

**Comment by Tai7sy** [comment]
https://service-hg2u0j5u-1251059978.gz.apigw.tencentcs.com/release/demo/test/%E9%99%88%E5%A5%95%E8%BF%85%20-%20%E6%8A%AB%E9%A3%8E.mp3/preview

已经支持部分格式预览功能
