### ISSUE TITLE
刚才更新的显示失败，如下

### ISSUE THREAD

**Issue by platoer** [Tai7sy/OneDriveFly#20]
`{"errorCode":-1,"errorMessage":"Process exited before completing request"}`

日志：
START RequestId: b689b480-bcde-11e9-a159-52540014ca86
Event RequestId: b689b480-bcde-11e9-a159-52540014ca86
Warning: include(vendor/autoload.php): failed to open stream: No such file or directory in /var/user/index.php on line 2

Warning: include(): Failed opening 'vendor/autoload.php' for inclusion (include_path='/var/user:/var/runtime/php7') in /var/user/index.php on line 2

Warning: include(functions.php): failed to open stream: No such file or directory in /var/user/index.php on line 3

Warning: include(): Failed opening 'functions.php' for inclusion (include_path='/var/user:/var/runtime/php7') in /var/user/index.php on line 3

Fatal error: Uncaught Error: Call to undefined function path_format() in /var/user/index.php:51

Stack trace:

#0 /var/runtime/php7/bootstrap.php(41): main_handler(Array, Array)

#1 /var/runtime/php7/bootstrap.php(189): __scf_bootstrap_\EventHandler->handle(Object(stdClass), Object(stdClass))

#2 /var/runtime/php7/bootstrap.php(212): __scf_bootstrap_\__main_for_scf()

#3 {main}

  thrown in /var/user/index.php on line 51

END RequestId: b689b480-bcde-11e9-a159-52540014ca86

Report RequestId: b689b480-bcde-11e9-a159-52540014ca86 Duration:14ms Memory:128MB MaxMemoryUsed:12.918MB

测试了几次一直这样

**Comment by qkqpttgf** [comment]
你的function.php不见了。你整体下载zip再上传到SCF吧。

**Comment by platoer** [comment]
嗯，确实是。上传了几次才成功！

**Comment by platoer** [comment]
> 你的function.php不见了。你整体下载zip再上传到SCF吧。

重新上传之后，填入refresh_token之后保存和测试就又回到这种错误了/
