### ISSUE TITLE
 html文件预览显示错误

### ISSUE THREAD

**Issue by platoer** [Tai7sy/OneDriveFly#21]
上一版本正常，更新后发现不能预览html文件，不知道是api限制还是小bug，如下：

{"errorCode":-1,"errorMessage":"Grpc invokeFunction error: rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4906398 vs. 4194304)"}

**Comment by qkqpttgf** [comment]
英文大意：文件快5M了，超出GRPC的限制。
GRPC是啥不知道，但你一个html文件弄这么大做什么，小说全本吗？
