### ISSUE TITLE
能不能添加md文件的预览

### ISSUE THREAD

**Issue by fl20002** [Tai7sy/OneDriveFly#3]
主要还是README.md 

从oneindex好搬迁

**Comment by Tai7sy** [comment]
已经加入
https://github.com/Tai7sy/OneDrive_SCF/commit/e2cd37e69fe9debf30b60afbc4beecf091c19cff

**Comment by fl20002** [comment]
能显示预览  但是不支持md格式 。。。

**Comment by Tai7sy** [comment]
不支持是什么意思？

**Comment by fl20002** [comment]
> 不支持是什么意思？

markdown的格式

![image](https://user-images.githubusercontent.com/18693963/58228453-5d2c6100-7d61-11e9-80c4-6fb97562b172.png)

现在显示的是左边    应该是右边的样子
