### ISSUE TITLE
是否可以支持MKV格式视频播放呢？

### ISSUE THREAD

**Issue by sjkgames** [Tai7sy/OneDriveFly#4]
onedrive上是可以MKV播放，在Qdrive上显示此文件预览不支持，希望能添加Mkv格式的支持

**Comment by Tai7sy** [comment]
https://github.com/Tai7sy/OneDrive_SCF/commit/f96bb8697022a7040652e1c954361cb114c0c8d9
刚才加上了, 至于浏览器是否兼容就不知道了

**Comment by sjkgames** [comment]
ok，已经兼容了！谢谢大佬
