### ISSUE TITLE
Index file or folder list is not opening

### ISSUE THREAD

**Issue by ashish453** [Tai7sy/OneDriveFly#40]
I successfully integrated index.php code in my server and it also shows the file content of the the folder whose path i entered in the code but the problem is when I try to open the particular file or folder it says page not found.

I think the problem is when I open indexed  file or folder, it search for that URL in my server or website rather than in onedrive.

**Comment by Tai7sy** [comment]
You should edit the rewrite rule of your web server

for example (Apache)
https://github.com/Tai7sy/OneDriveFly/blob/master/php/.htaccess

nginx
```
    if (!-e $request_filename)
    {
        rewrite ^/(.*)$ /index.php?/$1 last;
        break;
    }
```

**Comment by ashish453** [comment]
Brother Can't it be done on index.php given by your.
I mean it will be good if you provide me a code which will write the file name in adress bar after mydomain.com/files/index.php/filename instead of mydomain.com/filemane


Because there is already this code:
 RewriteRule ^index\.php$ - [L]
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteRule . /index.php [L]

in my .htacess 

so  i think adding your code in my .htacess will ruin my main site.

**Comment by Tai7sy** [comment]
Your can access your file via "mydomain.com/files/index.php/somepath/filename"

but the url in the list is broken, I will fix it soon.

**Comment by ashish453** [comment]
Thanks man i will be waiting. But for now i am using cloudflare redirect to add index.php

**Comment by Tai7sy** [comment]
fixed in e4df82f4469847698f5749f0b1ae3c4c198d4adb

**Comment by ashish453** [comment]
how can i use password in all files instead in particular directory?

**Comment by Tai7sy** [comment]
you can't.
bur you can use basic-http-auth
https://www.digitalocean.com/community/tutorials/how-to-set-up-basic-http-authentication-with-nginx-on-ubuntu-14-04
